### ISSUE TITLE
Blocks go of the edge of the screen on mobile phone around level ~170

### ISSUE THREAD

**Issue by MichaelGoulding** [matthijsgroen/block-sort#117]
Now that there are more blocks per column, I can't see the last row of blocks without switching to desktop mode on my phone, which is way too small.

**Comment by matthijsgroen** [comment]
Thanks for reporting!

What model phone do you have? This helps me with testing :-)

**Comment by MichaelGoulding** [comment]
It is a Samsung S21FE

Thanks for fixing.
