### ISSUE TITLE
Time limiter on saved games

### ISSUE THREAD

**Issue by godevan** [matthijsgroen/block-sort#59]
Hello, I like this game, it is good to learning matching. I read it has about 300 levels, but I can only complete a few levels in a day. The export function seems to have a 10 minute limit; is there anyway to adjust the timer so, I can save the game, and then reload it the next day when I turn on PC again?

**Comment by matthijsgroen** [comment]
The game export is only needed if you transfer from device. If you use a normal browser the data is kept and not wiped between days. There is no limit on the amount of levels. the highest difficulty (for now) is reached at level 268.

**Comment by matthijsgroen** [comment]
I mean, this import/export thing is new this week, and I've been playing on my phone for almost a month already, and did minor and major OS upgrades without losing data.

**Comment by godevan** [comment]
Thank you; it is a fun game. Perhaps I am doing it wrong. I use firefox on a PC, and I export the data, it shows a screen with a bar code. I take a screenshot of the bar code, and save it to my desktop. Then, I'll close the browser and shut off the PC; the next day I go back to the game page and load the data, but it says data is too old. If I close the browser/shut off the PC and then turn it on inside the 10 minute time limit, then it will load. What I am hoping for, is the time limit to go away so I can reload the game at the last saved spot the next day. I hope my explain is making sense, and thank you, I am enjoying the matching a lot.

**Comment by matthijsgroen** [comment]
Are you reset everytime to level 1? because that should not happen. Without the export / import you should be able to continue where you left.

**Comment by godevan** [comment]
Yes, so for example, yesterday I played until level 40, and I did the export and saved it to my desktop, then turned off the PC. Today, when I turn on the PC and go back to the page, it starts me at level 1, and when I try to import the screenshot, it says it is too old. I am using windows 7 with firefox. Is there some error that I am making? Or a way to save my progress that I am not understanding?

**Comment by matthijsgroen** [comment]
could you check in `about:preferences#privacy` if you have a setting where you clear all data after visit? The game uses an indexed DB to store its contents. Your browser probably clears it after each visit.

**Comment by godevan** [comment]
I can see the settings and it seems to be set to "delete cookies and data upon closing". However, I can't see how to uncheck it, and to be honest my nephew set up my PC for me to safe. I was able to add your site to the whitelist, but that did not fix the situation. The export import does work, but limited to 10 minutes. Would it be possible to change/remove the 10 minute limit? Otherwise it says like "data is too old" and will not load. Sorry to be asking technical things that are mostly beyond my understanding, I like your game and I can still play, just unlikely I'll ever get to the higher levels but it's not just the time in the day limit, probably my brain has limits as well, haha. Thank you for all your help and if the time limit cannot be removed, I understand.

**Comment by matthijsgroen** [comment]
Are you sure you added `https://matthijsgroen.github.io/block-sort` as address? The problem with large time limits is that will limit me in how QR codes are supported in the future, since I then have to support data formats from older versions of the game. Have you tried playing the game on a smartphone or tablet?

**Comment by godevan** [comment]
Thank you; I did add it but it always removes the /block-sort part. I will ask my nephew next time he visits to help me to see what I am doing wrong. I don't have a tablet but I do have a phone, but sadly it's too small for me to use. I understand what you mean about time limits for saved games and the older versions, so I can see how that is not possible. I very much appreciate all of your patience and support, and when my nephew visits I will show him all of this and ask him to help. It's a great game, thank you for making it.

**Comment by godevan** [comment]
I have some good news, my nephew showed me how to play the game on my phone. But, one small issue, I made it to the "wizard line" and the block stack became 7,not 6. However, the lower row does not fit onto the phone screen, and there seems to be no way to resize. Is there a way to make the game fit so both rows show all 7 blocks? I tried the button "show desktop site" but it was then super tiny. Still having a lot of fun, hopefully this can be repaired and I can try to get to 200.

**Comment by godevan** [comment]
Wow, that was very fast, thank you! Now it loaded again and I can see all the 7 blocks of each row. I managed to beat 166; however when it goes to load 167 it says failed to load 167, error message n.findLastIndex is not a function (some spelling may be incorrect, I have a hard time seeing on the phone). If that is something I can fix, kindly tell me how. Still having fun, thank you for a fun game.

**Comment by matthijsgroen** [comment]
I will look into it, thanks for the feedback!

**Comment by matthijsgroen** [comment]
It should be fixed now as well!

**Comment by matthijsgroen** [comment]
I will close this issue now. If you have more feedback, please open a new issue :-D Thanks again for playing the game!
