### ISSUE TITLE
Game gives hints that will result in a loss

### ISSUE THREAD

**Issue by lzwanenberg** [matthijsgroen/block-sort#71]
On level 137, following all hints from the start will result in a loss (see image). I would expect hints to always point in the right direction.

Version: 1.10.4

![Screenshot_20241019_074232_Chrome](https://github.com/user-attachments/assets/1049cad2-3e60-4630-aa25-a179402e7a19)

**Comment by matthijsgroen** [comment]
Noe, becaue they are not hints :-) It's actually an indication of your previous play-through. I'm adding a help screen to the game now explaining the concept.

### Ghost hand 👇

Don't be scared, it's just a friendly ghost indication how your previous play was before you got **blocked**. Will you follow in your own footsteps and get blocked in the same way? Or will you change your fate and your puzzle outcome?

**Comment by matthijsgroen** [comment]
(I wanted to use the hand of a skeleton, but that is unfortunately not available)
